# -*- coding: utf-8 -*-
"""Conditional_statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYFtuAXWUglE-Ctovy3ZgoCBCK5c8Wl6
"""

# 1. Check if a number is positive, negative, or zero
# Write a Python program that takes a number as input and checks whether it is positive, negative, or zero.

# 2. Check if a number is even or odd
# Write a Python program that asks the user to enter a number and determines if it is even or odd.

# 3. Find the largest of two numbers
# Write a Python program that takes two numbers as input and prints the largest one.

# 4. Find the largest of three numbers
# Write a Python program that takes three numbers as input and determines the largest of the three.

# 5. Check if a year is a leap year
# Write a Python program that takes a year as input and checks whether it is a leap year or not.

# 6. Grade a student based on marks
# Write a Python program that asks the user to enter their marks and assigns a grade based on the following:

# 90-100: A
# 80-89: B
# 70-79: C
# 60-69: D
# Below 60: Fail


# 7. Check if a number is divisible by both 5 and 11
# Write a Python program that takes a number as input and checks if it is divisible by both 5 and 11.

# 8. Check if a character is a vowel or consonant
# Write a Python program that takes a single character as input and checks whether it is a vowel (a, e, i, o, u) or a consonant.

# 9. Check if a number is within a specific range
# Write a Python program that checks whether a given number lies between 10 and 50 (inclusive).

# 10. Check if a person is eligible to vote
# Write a Python program that asks for a person's age and checks if they are eligible to vote (age ≥ 18).

num = int(input("Enter the number: "))

if(num>0):
  print("Positive")
elif(num==0):
  print("Zero")
elif(num<0):
  print("Negative")
else:
  print("Invalid input")

num =int(input("Enter a number: "))

if(num%2==0):
  print("Even")
else:
  print("Odd")

num1 = int(input("Enter First value: "))
num2 = int(input("Enter second value: "))

if(num1>num2):
  print(num1,"is greater...")
elif(num1<num2):
  print(num2,"is greater...")
elif(num1==num2):
  print("Both are equal...")
else:
  print("Invalid input value")

num1 = int(input("Enterfirst value"))
num2 = int(input("Enter second value"))
num3 = int(input("Enter third value"))

if(num1>num2):
  if(num1>num3):
    print(num1,"is greater...")
  else:
    print(num3,'is greater...')
elif(num2>num1):
  if(num2>num3):
    print(num2,"is greater...")
  else:
    print(num3,'is greater...')
elif(num1==num2==num3):
  print("All are equal values...")
else:
  print("invalid input, Enter a integer value...")

year = int(input("Enter the Year: "))

if(year%4==0):
  print("Leap year")
else:
  print("Non-Leap year")

score = int(input("Enter your score: "))

if(score>=90 and score<=100):
  print("A")
elif(score>=80 and score<=89):
  print("B")
elif(score>=70 and score<=79):
  print("C")
elif(score>=60 and score<=69):
  print("D")
elif(score<60):
  print("Fail")

num = int(input("Enter the number: "))
if(num%5==0 and num%11==0):
  print("Number is divisible by both 5 and 11")
else:
  print("Not divisible by 5 and 11")

char = input("Enter a character: ")

if(char == 'a' or char == 'e' or char == 'i' or char =='o' or char =='u'):
  print("Vowel")
else:
  print("Consonent")

num =int(input("Enter the number: "))

if(num>=10 and num<=50):
  print("Number is within range")
else:
  print("Not in range")

age = int(input("Enter your age: "))

if(age>=18):
  print("You can vote")
else:
  print("You can't vote")

seat_available = 100
ticket_needed = int(input("Enter seat required: "))

if(seat_available==0):
  print("No seats are available...")
elif(ticket_needed > seat_available):
  print("Only",seat_available," are available")
elif(seat_available > ticket_needed):
  total_bill = ticket_needed * 100
  print("Total bill is: ",total_bill)
  seat_available = seat_available - ticket_needed
  print("Available seats are: ",seat_available)
else:
  print("Invalid input")

